// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX89HwAgclAESzLejixCg3_aie2sAyWvU',
    appId: '1:647712572014:web:1bd181781f3a9d180ddc7f',
    messagingSenderId: '647712572014',
    projectId: 'easyeducation-c7a23',
    authDomain: 'easyeducation-c7a23.firebaseapp.com',
    storageBucket: 'easyeducation-c7a23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADIQn4GwFEjh8FrP1bLV9mebz-dMSDADI',
    appId: '1:647712572014:android:a95ec0581a68aca40ddc7f',
    messagingSenderId: '647712572014',
    projectId: 'easyeducation-c7a23',
    storageBucket: 'easyeducation-c7a23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNHpUI4vI2kvSWS25L_te6vkyCe4MGQiw',
    appId: '1:647712572014:ios:0cc89f116d8c84020ddc7f',
    messagingSenderId: '647712572014',
    projectId: 'easyeducation-c7a23',
    storageBucket: 'easyeducation-c7a23.appspot.com',
    iosBundleId: 'com.vikash.easyEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNHpUI4vI2kvSWS25L_te6vkyCe4MGQiw',
    appId: '1:647712572014:ios:8ce12d990bcc3c940ddc7f',
    messagingSenderId: '647712572014',
    projectId: 'easyeducation-c7a23',
    storageBucket: 'easyeducation-c7a23.appspot.com',
    iosBundleId: 'com.vikash.easyEducation.RunnerTests',
  );
}
